const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
const SET_QUESTION_ANSWER = 'SET_QUESTION_ANSWER';
const SAVE_QUESTION = 'SAVE_QUESTION';


export default {
	RECEIVE_QUESTIONS,
	SET_QUESTION_ANSWER,
	SAVE_QUESTION
};
